# Generated by Django 4.0 on 2021-12-27 02:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=200, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.module', verbose_name='Modulo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
