# Generated by Django 4.0 on 2021-12-27 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='module_id',
            new_name='module',
        ),
    ]
