# Generated by Django 4.0 on 2021-12-30 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
        ('classes', '0002_rename_module_id_class_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='modules.module', verbose_name='Modulo'),
        ),
    ]
